// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/proto/scheduler.proto

package scheduler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskCoordinator_StreamMetrics_FullMethodName = "/scheduler.TaskCoordinator/StreamMetrics"
)

// TaskCoordinatorClient is the client API for TaskCoordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service handling metrics collection and check tasks
type TaskCoordinatorClient interface {
	// Client-to-Server stream for processing normalized metrics
	StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricPayload, MetricsSummaryResponse], error)
}

type taskCoordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskCoordinatorClient(cc grpc.ClientConnInterface) TaskCoordinatorClient {
	return &taskCoordinatorClient{cc}
}

func (c *taskCoordinatorClient) StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricPayload, MetricsSummaryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskCoordinator_ServiceDesc.Streams[0], TaskCoordinator_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricPayload, MetricsSummaryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskCoordinator_StreamMetricsClient = grpc.ClientStreamingClient[MetricPayload, MetricsSummaryResponse]

// TaskCoordinatorServer is the server API for TaskCoordinator service.
// All implementations must embed UnimplementedTaskCoordinatorServer
// for forward compatibility.
//
// Service handling metrics collection and check tasks
type TaskCoordinatorServer interface {
	// Client-to-Server stream for processing normalized metrics
	StreamMetrics(grpc.ClientStreamingServer[MetricPayload, MetricsSummaryResponse]) error
	mustEmbedUnimplementedTaskCoordinatorServer()
}

// UnimplementedTaskCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskCoordinatorServer struct{}

func (UnimplementedTaskCoordinatorServer) StreamMetrics(grpc.ClientStreamingServer[MetricPayload, MetricsSummaryResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedTaskCoordinatorServer) mustEmbedUnimplementedTaskCoordinatorServer() {}
func (UnimplementedTaskCoordinatorServer) testEmbeddedByValue()                         {}

// UnsafeTaskCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskCoordinatorServer will
// result in compilation errors.
type UnsafeTaskCoordinatorServer interface {
	mustEmbedUnimplementedTaskCoordinatorServer()
}

func RegisterTaskCoordinatorServer(s grpc.ServiceRegistrar, srv TaskCoordinatorServer) {
	// If the following call panics, it indicates UnimplementedTaskCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskCoordinator_ServiceDesc, srv)
}

func _TaskCoordinator_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskCoordinatorServer).StreamMetrics(&grpc.GenericServerStream[MetricPayload, MetricsSummaryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskCoordinator_StreamMetricsServer = grpc.ClientStreamingServer[MetricPayload, MetricsSummaryResponse]

// TaskCoordinator_ServiceDesc is the grpc.ServiceDesc for TaskCoordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskCoordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.TaskCoordinator",
	HandlerType: (*TaskCoordinatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _TaskCoordinator_StreamMetrics_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/scheduler.proto",
}
