// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/scheduler.proto

package scheduler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Normalized event payload generated by workers
type MetricPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // e.g., "SUCCESS", "FAILED"
	LatencyMs     int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Payload       string                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"` // Raw error text or unmarshaled RESTCONF response
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CollectorId   string                 `protobuf:"bytes,8,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"` // Identifies which remote machine ran the check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPayload) Reset() {
	*x = MetricPayload{}
	mi := &file_api_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPayload) ProtoMessage() {}

func (x *MetricPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPayload.ProtoReflect.Descriptor instead.
func (*MetricPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *MetricPayload) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *MetricPayload) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MetricPayload) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *MetricPayload) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MetricPayload) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *MetricPayload) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *MetricPayload) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricPayload) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

type MetricsSummaryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalProcessed int64                  `protobuf:"varint,1,opt,name=total_processed,json=totalProcessed,proto3" json:"total_processed,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MetricsSummaryResponse) Reset() {
	*x = MetricsSummaryResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSummaryResponse) ProtoMessage() {}

func (x *MetricsSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSummaryResponse.ProtoReflect.Descriptor instead.
func (*MetricsSummaryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsSummaryResponse) GetTotalProcessed() int64 {
	if x != nil {
		return x.TotalProcessed
	}
	return 0
}

func (x *MetricsSummaryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_scheduler_proto protoreflect.FileDescriptor

const file_api_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/scheduler.proto\x12\tscheduler\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x02\n" +
	"\rMetricPayload\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\x12\x18\n" +
	"\apayload\x18\x06 \x01(\tR\apayload\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\fcollector_id\x18\b \x01(\tR\vcollectorId\"[\n" +
	"\x16MetricsSummaryResponse\x12'\n" +
	"\x0ftotal_processed\x18\x01 \x01(\x03R\x0etotalProcessed\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2a\n" +
	"\x0fTaskCoordinator\x12N\n" +
	"\rStreamMetrics\x12\x18.scheduler.MetricPayload\x1a!.scheduler.MetricsSummaryResponse(\x01B!Z\x1f./api/proto/scheduler;schedulerb\x06proto3"

var (
	file_api_proto_scheduler_proto_rawDescOnce sync.Once
	file_api_proto_scheduler_proto_rawDescData []byte
)

func file_api_proto_scheduler_proto_rawDescGZIP() []byte {
	file_api_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_api_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_scheduler_proto_rawDesc), len(file_api_proto_scheduler_proto_rawDesc)))
	})
	return file_api_proto_scheduler_proto_rawDescData
}

var file_api_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_scheduler_proto_goTypes = []any{
	(*MetricPayload)(nil),          // 0: scheduler.MetricPayload
	(*MetricsSummaryResponse)(nil), // 1: scheduler.MetricsSummaryResponse
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
}
var file_api_proto_scheduler_proto_depIdxs = []int32{
	2, // 0: scheduler.MetricPayload.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: scheduler.TaskCoordinator.StreamMetrics:input_type -> scheduler.MetricPayload
	1, // 2: scheduler.TaskCoordinator.StreamMetrics:output_type -> scheduler.MetricsSummaryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_scheduler_proto_init() }
func file_api_proto_scheduler_proto_init() {
	if File_api_proto_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_scheduler_proto_rawDesc), len(file_api_proto_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_api_proto_scheduler_proto_depIdxs,
		MessageInfos:      file_api_proto_scheduler_proto_msgTypes,
	}.Build()
	File_api_proto_scheduler_proto = out.File
	file_api_proto_scheduler_proto_goTypes = nil
	file_api_proto_scheduler_proto_depIdxs = nil
}
