// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/proto/collector.proto

package collector

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonitoringService_StreamJobs_FullMethodName    = "/collector.MonitoringService/StreamJobs"
	MonitoringService_StreamResults_FullMethodName = "/collector.MonitoringService/StreamResults"
)

// MonitoringServiceClient is the client API for MonitoringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service handling orchestration between Scheduler Server and Remote Collectors
type MonitoringServiceClient interface {
	// Bidirectional stream: Collector registers, Server pushes jobs dynamically
	StreamJobs(ctx context.Context, in *StreamJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MonitorJob], error)
	// Client-to-Server stream: Collector streams normalized events back to Server
	StreamResults(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UnifiedEvent, StreamResultsResponse], error)
}

type monitoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitoringServiceClient(cc grpc.ClientConnInterface) MonitoringServiceClient {
	return &monitoringServiceClient{cc}
}

func (c *monitoringServiceClient) StreamJobs(ctx context.Context, in *StreamJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MonitorJob], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MonitoringService_ServiceDesc.Streams[0], MonitoringService_StreamJobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamJobsRequest, MonitorJob]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitoringService_StreamJobsClient = grpc.ServerStreamingClient[MonitorJob]

func (c *monitoringServiceClient) StreamResults(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UnifiedEvent, StreamResultsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MonitoringService_ServiceDesc.Streams[1], MonitoringService_StreamResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UnifiedEvent, StreamResultsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitoringService_StreamResultsClient = grpc.ClientStreamingClient[UnifiedEvent, StreamResultsResponse]

// MonitoringServiceServer is the server API for MonitoringService service.
// All implementations must embed UnimplementedMonitoringServiceServer
// for forward compatibility.
//
// Service handling orchestration between Scheduler Server and Remote Collectors
type MonitoringServiceServer interface {
	// Bidirectional stream: Collector registers, Server pushes jobs dynamically
	StreamJobs(*StreamJobsRequest, grpc.ServerStreamingServer[MonitorJob]) error
	// Client-to-Server stream: Collector streams normalized events back to Server
	StreamResults(grpc.ClientStreamingServer[UnifiedEvent, StreamResultsResponse]) error
	mustEmbedUnimplementedMonitoringServiceServer()
}

// UnimplementedMonitoringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitoringServiceServer struct{}

func (UnimplementedMonitoringServiceServer) StreamJobs(*StreamJobsRequest, grpc.ServerStreamingServer[MonitorJob]) error {
	return status.Error(codes.Unimplemented, "method StreamJobs not implemented")
}
func (UnimplementedMonitoringServiceServer) StreamResults(grpc.ClientStreamingServer[UnifiedEvent, StreamResultsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamResults not implemented")
}
func (UnimplementedMonitoringServiceServer) mustEmbedUnimplementedMonitoringServiceServer() {}
func (UnimplementedMonitoringServiceServer) testEmbeddedByValue()                           {}

// UnsafeMonitoringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitoringServiceServer will
// result in compilation errors.
type UnsafeMonitoringServiceServer interface {
	mustEmbedUnimplementedMonitoringServiceServer()
}

func RegisterMonitoringServiceServer(s grpc.ServiceRegistrar, srv MonitoringServiceServer) {
	// If the following call panics, it indicates UnimplementedMonitoringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonitoringService_ServiceDesc, srv)
}

func _MonitoringService_StreamJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamJobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonitoringServiceServer).StreamJobs(m, &grpc.GenericServerStream[StreamJobsRequest, MonitorJob]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitoringService_StreamJobsServer = grpc.ServerStreamingServer[MonitorJob]

func _MonitoringService_StreamResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MonitoringServiceServer).StreamResults(&grpc.GenericServerStream[UnifiedEvent, StreamResultsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitoringService_StreamResultsServer = grpc.ClientStreamingServer[UnifiedEvent, StreamResultsResponse]

// MonitoringService_ServiceDesc is the grpc.ServiceDesc for MonitoringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "collector.MonitoringService",
	HandlerType: (*MonitoringServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJobs",
			Handler:       _MonitoringService_StreamJobs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamResults",
			Handler:       _MonitoringService_StreamResults_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/collector.proto",
}
