// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/collector.proto

package collector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtocolType int32

const (
	ProtocolType_PROTOCOL_UNSPECIFIED ProtocolType = 0
	ProtocolType_ICMP                 ProtocolType = 1
	ProtocolType_RESTCONF             ProtocolType = 2
	ProtocolType_SYSLOG               ProtocolType = 3
)

// Enum value maps for ProtocolType.
var (
	ProtocolType_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "ICMP",
		2: "RESTCONF",
		3: "SYSLOG",
	}
	ProtocolType_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"ICMP":                 1,
		"RESTCONF":             2,
		"SYSLOG":               3,
	}
)

func (x ProtocolType) Enum() *ProtocolType {
	p := new(ProtocolType)
	*p = x
	return p
}

func (x ProtocolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_collector_proto_enumTypes[0].Descriptor()
}

func (ProtocolType) Type() protoreflect.EnumType {
	return &file_api_proto_collector_proto_enumTypes[0]
}

func (x ProtocolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolType.Descriptor instead.
func (ProtocolType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_collector_proto_rawDescGZIP(), []int{0}
}

type StreamJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectorId   string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamJobsRequest) Reset() {
	*x = StreamJobsRequest{}
	mi := &file_api_proto_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamJobsRequest) ProtoMessage() {}

func (x *StreamJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamJobsRequest.ProtoReflect.Descriptor instead.
func (*StreamJobsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_collector_proto_rawDescGZIP(), []int{0}
}

func (x *StreamJobsRequest) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

type MonitorJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Protocol      ProtocolType           `protobuf:"varint,3,opt,name=protocol,proto3,enum=collector.ProtocolType" json:"protocol,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorJob) Reset() {
	*x = MonitorJob{}
	mi := &file_api_proto_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorJob) ProtoMessage() {}

func (x *MonitorJob) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorJob.ProtoReflect.Descriptor instead.
func (*MonitorJob) Descriptor() ([]byte, []int) {
	return file_api_proto_collector_proto_rawDescGZIP(), []int{1}
}

func (x *MonitorJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *MonitorJob) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MonitorJob) GetProtocol() ProtocolType {
	if x != nil {
		return x.Protocol
	}
	return ProtocolType_PROTOCOL_UNSPECIFIED
}

func (x *MonitorJob) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type UnifiedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Protocol      ProtocolType           `protobuf:"varint,3,opt,name=protocol,proto3,enum=collector.ProtocolType" json:"protocol,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // e.g., "SUCCESS", "FAILED"
	LatencyMs     int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Payload       string                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"` // Raw data dump or error strings
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnifiedEvent) Reset() {
	*x = UnifiedEvent{}
	mi := &file_api_proto_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedEvent) ProtoMessage() {}

func (x *UnifiedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedEvent.ProtoReflect.Descriptor instead.
func (*UnifiedEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_collector_proto_rawDescGZIP(), []int{2}
}

func (x *UnifiedEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UnifiedEvent) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *UnifiedEvent) GetProtocol() ProtocolType {
	if x != nil {
		return x.Protocol
	}
	return ProtocolType_PROTOCOL_UNSPECIFIED
}

func (x *UnifiedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UnifiedEvent) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *UnifiedEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *UnifiedEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StreamResultsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProcessedCount int32                  `protobuf:"varint,2,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamResultsResponse) Reset() {
	*x = StreamResultsResponse{}
	mi := &file_api_proto_collector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResultsResponse) ProtoMessage() {}

func (x *StreamResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_collector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResultsResponse.ProtoReflect.Descriptor instead.
func (*StreamResultsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_collector_proto_rawDescGZIP(), []int{3}
}

func (x *StreamResultsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamResultsResponse) GetProcessedCount() int32 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

var File_api_proto_collector_proto protoreflect.FileDescriptor

const file_api_proto_collector_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/collector.proto\x12\tcollector\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n" +
	"\x11StreamJobsRequest\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\"\x8f\x01\n" +
	"\n" +
	"MonitorJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x123\n" +
	"\bprotocol\x18\x03 \x01(\x0e2\x17.collector.ProtocolTypeR\bprotocol\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\"\xfd\x01\n" +
	"\fUnifiedEvent\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x123\n" +
	"\bprotocol\x18\x03 \x01(\x0e2\x17.collector.ProtocolTypeR\bprotocol\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\x12\x18\n" +
	"\apayload\x18\x06 \x01(\tR\apayload\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"Z\n" +
	"\x15StreamResultsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fprocessed_count\x18\x02 \x01(\x05R\x0eprocessedCount*L\n" +
	"\fProtocolType\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04ICMP\x10\x01\x12\f\n" +
	"\bRESTCONF\x10\x02\x12\n" +
	"\n" +
	"\x06SYSLOG\x10\x032\xa6\x01\n" +
	"\x11MonitoringService\x12C\n" +
	"\n" +
	"StreamJobs\x12\x1c.collector.StreamJobsRequest\x1a\x15.collector.MonitorJob0\x01\x12L\n" +
	"\rStreamResults\x12\x17.collector.UnifiedEvent\x1a .collector.StreamResultsResponse(\x01B!Z\x1f./api/proto/collector;collectorb\x06proto3"

var (
	file_api_proto_collector_proto_rawDescOnce sync.Once
	file_api_proto_collector_proto_rawDescData []byte
)

func file_api_proto_collector_proto_rawDescGZIP() []byte {
	file_api_proto_collector_proto_rawDescOnce.Do(func() {
		file_api_proto_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_collector_proto_rawDesc), len(file_api_proto_collector_proto_rawDesc)))
	})
	return file_api_proto_collector_proto_rawDescData
}

var file_api_proto_collector_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_collector_proto_goTypes = []any{
	(ProtocolType)(0),             // 0: collector.ProtocolType
	(*StreamJobsRequest)(nil),     // 1: collector.StreamJobsRequest
	(*MonitorJob)(nil),            // 2: collector.MonitorJob
	(*UnifiedEvent)(nil),          // 3: collector.UnifiedEvent
	(*StreamResultsResponse)(nil), // 4: collector.StreamResultsResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_api_proto_collector_proto_depIdxs = []int32{
	0, // 0: collector.MonitorJob.protocol:type_name -> collector.ProtocolType
	0, // 1: collector.UnifiedEvent.protocol:type_name -> collector.ProtocolType
	5, // 2: collector.UnifiedEvent.timestamp:type_name -> google.protobuf.Timestamp
	1, // 3: collector.MonitoringService.StreamJobs:input_type -> collector.StreamJobsRequest
	3, // 4: collector.MonitoringService.StreamResults:input_type -> collector.UnifiedEvent
	2, // 5: collector.MonitoringService.StreamJobs:output_type -> collector.MonitorJob
	4, // 6: collector.MonitoringService.StreamResults:output_type -> collector.StreamResultsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_collector_proto_init() }
func file_api_proto_collector_proto_init() {
	if File_api_proto_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_collector_proto_rawDesc), len(file_api_proto_collector_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_collector_proto_goTypes,
		DependencyIndexes: file_api_proto_collector_proto_depIdxs,
		EnumInfos:         file_api_proto_collector_proto_enumTypes,
		MessageInfos:      file_api_proto_collector_proto_msgTypes,
	}.Build()
	File_api_proto_collector_proto = out.File
	file_api_proto_collector_proto_goTypes = nil
	file_api_proto_collector_proto_depIdxs = nil
}
